services:
  - type: web
    name: llm-data-pipeline
    env: python
    plan: free
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements-deploy.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
